apiVersion: v1
kind: ReplicationController
metadata:
  name: web1
spec:
  replicas: 3
  selector:
    app: web1
  template:
    metadata:
      name: web1
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: nginx:1.7.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

